{
 "title": "YaFaD_ai Biomass Tiers",
 "description": "migration panel",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "total biomass",
   "type": "stat",
   "description": "total records",
   "gridPos": { "h": 3, "w": 1, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "yafad_total_biomass", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logs/sec",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 23, "x": 1, "y": 0 },
   "targets": [
    {
     "expr": "rate(yafad_log_messages_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "YaFaD_ai Biomass Tiers (T0-T4)",
   "type": "timeseries",
   "description": "migration panel",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "yafad_state_value", "legendFormat": "{{state_index}}" }
   ]
  },
  {
   "title": "Phi Diff / Lamda",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    { "expr": "yafad_phi_diff_value", "legendFormat": "Phi-diff" },
    { "expr": "yafad_lambda_value", "legendFormat": "Lambda (Flow Rate)" }
   ]
  }
 ]
}